# Generated by Django 3.2.6 on 2021-09-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('amt', models.IntegerField()),
                ('mtd', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('cancel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=50)),
                ('ostation', models.CharField(max_length=50)),
                ('dstation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('sid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('tno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=50)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('atime', models.CharField(max_length=50)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway.route')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway.station')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway.trains')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('nos', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('amt', models.IntegerField()),
                ('cls', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pnr', models.CharField(max_length=50)),
                ('src', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=50)),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway.trains')),
            ],
        ),
    ]
